<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="common_properties.xacro" />


    <xacro:property name="forearm_length" value = "0.3" />
    <xacro:property name="forearm_radius" value = "0.02" />
    <xacro:property name="hand_length" value = "0.3" />
    <xacro:property name="hand_radius" value = "0.02" />
    <xacro:property name="box_length" value = "0.1" />
    <xacro:property name="box_width" value = "0.1" />
    <xacro:property name="box_height" value = "0.02" />

    <link name = "base_footprint" />

    <link name="box_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" l="${2*box_length}" w="${2*box_width}" h="${2*box_height}" 
                           xyz="0 0 ${box_height}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius = "${forearm_radius}" length = "${forearm_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*forearm_radius}" h="${2*forearm_length}"
                       xyz="0 0 0" rpy="$0 0 0" />
    </link>



    <!-- <link name="hand_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" 
                           xyz="0 0 ${base_height}" rpy="0 0 0" />
    </link> -->

    <joint name= "base_joint" type ="fixed">
        <parent link = "base_footprint" />
        <child link = "box_link" />
        <origin xyz = "0 0 0" rpy = "0 0 0" />
    </joint>

    <joint name= "base_joint" type ="fixed">
        <parent link = "box_link" />
        <child link = "forearm_link" />
        <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0" />
        <axis xyz = "1 0 0" />
    </joint>


</robot>
