<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">




    <xacro:property name="forearm_length" value = "0.3" />
    <xacro:property name="forearm_radius" value = "0.02" />
    <xacro:property name="hand_length" value = "0.3" />
    <xacro:property name="hand_radius" value = "0.02" />
    <xacro:property name="box_length" value = "0.1" />
    <xacro:property name="box_width" value = "0.1" />
    <xacro:property name="box_height" value = "0.02" />
<!-- 
    <link name = "base_footprint" /> -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}" />
            </geometry>
            <origin xyz="0 0 ${box_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" l="${2*box_length}" w="${2*box_width}" h="${2*box_height}" 
                           xyz="0 0 ${box_height}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius = "${forearm_radius}" length = "${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:rod_inertia m="0.3" r="${2*forearm_radius}" h="${2*forearm_length}"
                       xyz="0 0 0" rpy="$0 0 0" />
    </link>



    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius = "${hand_radius}" length = "${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "${hand_radius}" length = "${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:rod_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- <joint name= "base_arm_base_joint" type ="fixed">
        <parent link = "base_link" />
        <child link = "arm_base_link" />
        <origin xyz = "0 0 ${base_height}" rpy = "0 0 0" />
    </joint> -->

    <joint name= "arm_base_forearm_joint" type ="revolute">
        <parent link = "arm_base_link" />
        <child link = "forearm_link" />
        <origin xyz="0 0 ${box_height}" rpy="0 0 0" />
        <axis xyz = "0 1 0" />
        <limit lower = "0" upper = "${pi/2.0}" effort = "100" velocity = "100" />
    </joint>

    <joint name= "forearm_hand_joint" type ="revolute">
        <parent link = "forearm_link" />
        <child link = "hand_link" />
        <origin xyz="0 0 ${hand_length}" rpy="0 0 0" />
        <axis xyz = "0 1 0" />
        <limit lower = "0" upper = "${pi/2.0}" effort = "100" velocity = "100" />
    </joint>


</robot>
